# service configuration for our dockerized Rails app
app:
  
  # use the Dockerfile next to this file
  build: .
  
  command: bundle exec rails s -p 3000 -b '0.0.0.0'    
  # sources environment variable configuration for our app
  env_file: .env
 
  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV
 
  # makes the app container aware of the DB container
  links:
    - db
 
  # expose the port we configured Unicorn to bind to
  ports:
    - "3000:3000"
  
  volumes:
    - .:/six-o-seven-app


db:
 
  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: postgres:9.4.5
 
  # persist the database between containers by storing it in a volume
  volumes:
    - six-o-seven-app-postgres:/var/lib/postgresql/data